/* eslint-disable */
import { FuseNavigationItem } from '@fuse/components/navigation'

export const defaultNavigation: FuseNavigationItem[] = [
  //   {
  //     id: 'example',
  //     title: 'Example',
  //     type: 'basic',
  //     icon: 'heroicons_outline:chart-pie',
  //     link: '/example',
  //   },
  //   {
  //     id: 'admin-permission',
  //     title: 'Permission',
  //     type: 'basic',
  //     icon: 'heroicons_outline:adjustments-vertical',
  //     link: '/admin-permission',
  //   },

  {
    id: 'admin-permission',
    title: 'Permission',
    type: 'basic',
    icon: 'heroicons_outline:adjustments-vertical',
    link: '/admin-permission',
  },
  {
    id: 'admin-role',
    title: 'Role',
    type: 'basic',
    icon: 'heroicons_outline:adjustments-vertical',
    link: '/admin-role',
  },
  {
    id: 'admin-user',
    title: 'Admin',
    type: 'basic',
    icon: 'heroicons_outline:adjustments-vertical',
    link: '/admin-user',
  },
  {
    id: 'tg-detail',
    title: 'Tg Detail',
    type: 'basic',
    icon: 'heroicons_outline:adjustments-vertical',
    link: '/tg-detail',
  },
  {
    id: 'translation',
    title: 'Translation',
    type: 'basic',
    icon: 'heroicons_outline:adjustments-vertical',
    link: '/translation',
  },
  {
    id: 'sp-premium-plan',
    title: 'Sp Premium Plan',
    type: 'basic',
    icon: 'heroicons_outline:adjustments-vertical',
    link: '/sp-premium-plan',
  },
  {
    id: 'sp-region',
    title: 'Region',
    type: 'basic',
    icon: 'heroicons_outline:adjustments-vertical',
    link: '/sp-region',
  },
  {
    id: 'sp-district',
    title: 'District',
    type: 'basic',
    icon: 'heroicons_outline:adjustments-vertical',
    link: '/sp-district',
  },
  {
    id: 'sp-category',
    title: 'Category',
    type: 'basic',
    icon: 'heroicons_outline:adjustments-vertical',
    link: '/sp-category',
  },
  {
    id: 'sp-sub-category',
    title: 'Sub Category',
    type: 'basic',
    icon: 'heroicons_outline:adjustments-vertical',
    link: '/sp-sub-category',
  },
  {
    id: 'client-resume',
    title: 'Resume',
    type: 'basic',
    icon: 'heroicons_outline:adjustments-vertical',
    link: '/client-resume',
  },
  {
    id: 'client-poster',
    title: 'Poster',
    type: 'basic',
    icon: 'heroicons_outline:adjustments-vertical',
    link: '/client-poster',
  },
  {
    id: 'client-user',
    title: 'Poster',
    type: 'basic',
    icon: 'heroicons_outline:adjustments-vertical',
    link: '/client-user',
  },
]
